sudo: false
install:
- "curl http://files.zerogw.com/vagga/vagga-install.sh | sudo sh"
- "echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml"
- "echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml"
script:
- vagga _build admin_service
